"""empty message

Revision ID: e2ea5f7453de
Revises: 
Create Date: 2023-12-11 23:14:24.218111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ea5f7453de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.String(length=20), nullable=False),
    sa.Column('emissor', sa.String(length=20), nullable=True),
    sa.Column('data_base', sa.DateTime(), nullable=True),
    sa.Column('data_liquidacao', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ativo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eventos')
    # ### end Alembic commands ###
